- R/get_match_report.R
- tests/testthat/test-fbref.R
Resolves JaseZiv/worldfootballR#2. In cases where a player who already has a yellow card receives another yellow card and a red card all three cards are counted, see for example the [Arsenal - Manchester City match from Jan 1st, 2022](https://fbref.com/en/matches/a9903a63/Arsenal-Manchester-City-January-1-2022-Premier-League).
```R
get_match_report(match_url = "https://fbref.com/en/matches/a9903a63/Arsenal-Manchester-City-January-1-2022-Premier-League") %>%
select(Home_Yellow_Cards, Home_Red_Cards, Away_Yellow_Cards, Away_Red_Cards)
```
|Home_Yellow_Cards |Home_Red_Cards |Away_Yellow_Cards |Away_Red_Cards |
|:-----------------|:--------------|:-----------------|:--------------|
|5                 |1              |2                 |0              |
> Add yellow and red card data to `get_match_report`

- R/fotmob_leagues.R
- tests/testthat/test-fotmob.R
The error message was not being correctly printed out when all of the countries/league_names are mis-specified in `fotmob_get_league_matches`.
> fix `fotmob_get_league_matches` error message

- DESCRIPTION
- NEWS.md
- R/fotmob_players.R
- tests/testthat/test-fotmob.R
Previously I was testing on domestic league matches and didn't realize that the `table` element in the JSON response for a non-domestic match would be just `FALSE` instead of an array of size 2 with the team ids. We are using the `table` element to "correct" for "bad" away team ids (see #93). In the case that the match is non-domestic, we resort to leaving the `away_team_id` as is.
fixes #111
> Fix team ids in non-domestic matches for `fotmob_get_match_players()`

- DESCRIPTION
- NEWS.md
- R/fotmob_leagues.R
- R/fotmob_matches.R
- R/fotmob_players.R
- R/fotmob_stats.R
- man/fotmob_get_season_stats.Rd
- tests/testthat/test-fotmob.R
- vignettes/extract-fotmob-data.Rmd
Fixes #121 and #122.
* `fotmob_get_leage_matches()` and `fotmob_get_league_tables()` after changes to names in JSON response (`fixtures` -> `matches`, `tableData` -> `table`) [#121](https://github.com/JaseZiv/worldfootballR/issues/121), [#122](https://github.com/JaseZiv/worldfootballR/issues/122)
* Various fotmob functions affected by addition of `api/` in URL
* New names to player stats outdated docs for `fotmob_get_season_stats()`
Evidence for tests passing locally:
> Various fotmob fixes

- DESCRIPTION
- NEWS.md
- R/fotmob_stats.R
Addresses logic for extracting season ids from season stats pages in  `fotmob_get_season_stats()`. This was failing due to blank stats pages in the off-season for a league.
Tests passed locally
> Fix `fotmob_get_season_stats`

- DESCRIPTION
- NEWS.md
- R/fotmob_players.R
- tests/testthat/test-fotmob.R
Fixes #150.
fotmob now returns the successful count, total, and percentage for percentage stats (e.g. Accuracy %). I think we should be "lazy", forcing every stat column to be a character. The onus is shifted to the user to coerce what they want to numerics.
For example, for accuracy %, the raw number of successful passes may be more interesting to the user than the accuracy %, so we leave the value as is (e.g. `4/5 (80%)`) and let the user extract what they want. Yes, this makes it inconvenient for a stat like goals, which is just reported as a count, forcing the user to always coerce goals to numeric from a character, but I think this design is ok. 
fotmob has changed their API a lot, and I think we want to reduce maintenance demand on our end. If we're returning characters for all …
> Return stats at characters in `fotmob_get_match_players()`

- DESCRIPTION
- NEWS.md
- R/fotmob_leagues.R
- tests/testthat/test-fotmob.R
Apparently there was an additional level of nesting introduced recently. Also, for a league like MLS, I found that `unnest`ing was broken due to `page_url` existing at multiple levels, causing an identical name conflict when unnesting. This is resolved by specifying `names_sep = "_"`, which introduces a prefix for names unnested.
> Fix `fotmob_get_league_tables`

- R/fotmob_matches.R
There was an issue with calling `fotmob_get_matches_by_date()` for future dates. fotmob doesn't return the `match_status_reason column` for such matches. The issue is resolved by dropping `match_status_reason`, which is typically a nested data frame that has redundant information with the other `match_status_ columns`, e.g. `match_status_finished`. The prior code was arguably brittle anyways.
```r
future <- c("20221017","20221025","20221027","20221028","20221031","20221101")
results <- fotmob_get_matches_by_date(dates = future)
str(results)
```
```
tibble [526 × 34] (S3: tbl_df/tbl/data.frame)
$ ccode                            : chr [1:526] "USA" "USA" "ESP" "ITA" ...
$ id                               : int [1:526] 881538 881538 87 55 55 879435 879435 879435 879435 879435 ...
$ …
```
> Fix `fotmob_get_matches_by_date()` for future match dates.

- DESCRIPTION
- R/load_fotmob.R
- tests/testthat/test-fotmob.R
I updated fotmob tests such that column order is no longer checked for. There was an issue with a test where it failed due to columns being returned in a different order.
> Update `load_fotmob_` functions to use data from releases

- DESCRIPTION
- NEWS.md
- R/get_match_shooting.R
Fixing an issue where team names are inconsistent on match pages, leading to all teams being designated `Away` when the home team name is inconsistent... see this page if you wanted an example https://fbref.com/en/matches/e62685d4/Manchester-United-Leeds-United-August-14-2021-Premier-League
`Manchester United` is the home team, however in the shot log table, they're `Manchester Utd`... have made this more robust now
> home_away incorrect for some games #219

- .Rbuildignore
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
The issue template will hopefully prompt users to try installing the latest of the version of the package before submitting their issue, which hopefully will result in less issues being filed. I copied some of the language from `{tidyverse}` packages.
I also added a `CONTRIBUTING.md` so that potential contributors will know how to contribute 😄 . (This was created with `usethis::use_tidy_contributing()`.)
> Add `CONTRIBUTING.md` and issue template

- DESCRIPTION
- NEWS.md
- R/fotmob_players.R
Fixed an issue with retrieving player data for future matches with `fotmob_get_match_players` due to the default value of `stats` (use `list(NULL)` instead of `NULL` so that `unnest_wider(data, stats)` works)
```r
packageVersion("worldfootballR")
#> [1] '0.6.1.5000'
options(tibble.print_min = 22)
fotmob_get_match_players(3370555) |> 
dplyr::select(
team_name,
shirt,
first_name,
last_name,
role
)
```
```
team_name shirt first_name last_name role      
<chr>     <chr> <chr>      <chr>     <chr>     
1 Japan     12    Shuichi    Gonda     Keeper    
2 Japan     16    Takehiro   Tomiyasu  Defender  
3 Japan     3     Shogo      Taniguchi Defender  
4 Japan     22    Maya       Yoshida   Defender  
5 Japan     14    Junya      Ito       Attacker  
6 Japan     13    Hidemasa   Morita …
```
> Fix #226 (future match lineups from fotmob)

- DESCRIPTION
- NEWS.md
- R/fotmob_leagues.R
- tests/testthat/test-fotmob.R
`fotmob_get_league_matches()` was failing due to an extra `purrr::map_dfr` that is no longer needed [#229](https://github.com/JaseZiv/worldfootballR/issues/229)
Also, I updated some of the fotmob tests that were failing due to changes in the column names provided by Fotmob.
> Fix #229 and fotmob tests

- DESCRIPTION
- NEWS.md
- R/internals.R
- R/player_transfer_history.R
- man/tm_player_transfer_history.Rd
- vignettes/extract-transfermarkt-data.Rmd
First of all, I had problems scraping market values as I have 'k' instead of 'th' when talking thousands (€500k instead of €500th for example) so I added that case in `.convert_value_to_numeric`.
Then I added a parameter in `tm_player_transfer_history`, defaulting to true, to allow users to avoid scraping extra info that increase hugely the computation time of the function. From my latest tests on more obscure players sometimes the function needs 40/50s to be executed due to multiple calls to `extra_info <- tryCatch(xml2::read_html(extra_info_url), error = function(e) NA)`. 
The country_to/from field is no more obtainable from the initial summary page, but the information is present in (most) transfer details views, so now the country will be scraped if `get_extra_info` is `TRUE`. …
> Changed transfer_history logic + added case 'k' in MV conversion

- DESCRIPTION
- NEWS.md
- R/fotmob_matches.R
- R/fotmob_players.R
- R/fotmob_stats.R
- R/understat_teams.R
- R/worldfootballr_helpers.R
Use `quiet = FALSE` in all `purrr::possibly()` calls internally. Improve messaging for unexpected outcomes in `fotmob_get_matches_by_date()` and `fotmob_get_match_info()`.
Addresses #244.
> Improve messaging for silent failures

- DESCRIPTION
- NEWS.md
- R/fotmob_matches.R
- tests/testthat/test-fotmob.R
I realized that the issue with [the fotmob match details scraper](https://github.com/JaseZiv/worldfootballR_data/actions/runs/4158784531/jobs/7194236210) returning lots of errors for `janitor::clean_names()` is due to some faulty logic for handling matches without shots. I've addressed this, which should eliminate all the errors I was seeing in the data repo's GitHub Action.
> Fix `fotmob_get_match_details()` for matches without shot details

- DESCRIPTION
- NEWS.md
- R/fotmob_leagues.R
- tests/testthat/test-fotmob.R
It seems that they removed/renamed the `matches.data.matchesCombinedByRound` element...
Fixes #258
> Fix `fotmob_get_league_matches()`

- DESCRIPTION
- NEWS.md
- R/fotmob_leagues.R
- R/fotmob_matches.R
- tests/testthat/test-fotmob.R
- Fix issue with duplicate names returned by `fotmob_get_league_ids()`. (This affected several functions.) This is due to the addition of `localizedName` in the API response.
- Stop returning `home_team_color` and `away_team_color` in fotmob match functions. Fotmob has changed the format twice in the span of a month (see #272) and may continue to change the format for all we know. I think these are low value columns.
- Refactor all Fotmob tests that check for columns to be less strict. 
Fixes #275
> Fix fotmob colors again

- DESCRIPTION
- NEWS.md
- R/get_season_team_stats.R
- man/fotmob_get_league_tables.Rd
#282
The "league_table_home_away" part now filters the "home_away" table even if it isn't the second table in the list.
Doing the same for the "league_table" argument by searching for the "overall" string isn't as simple... there can be several tables with "overall", see below for [Liga MX 2019-20](https://fbref.com/en/comps/31/2019-2020/).
It could be hard-coded in the same way that MLS is (in the if statements with "Conference"), or some other method to identify the right "overall" league table more robustly.
> Fix fb home away tables

- DESCRIPTION
- NEWS.md
- R/fotmob_stats.R
The function was printing out `Error: no applicable method for 'distinct' applied to an object of class "list"` due to attempting to scrape data for 2023/24, since the season option is shown in the menu, but there is no data yet for it. One solution could be to set `quiet = TRUE` in the `possibly()` function that wraps the helper function that does scraping, but I like to see people report issues for subtle things like this. The solution I've implemented is a "short-cut" exit from the scraper when no data is detected.
Fixes #297.
> Eliminate `fotmob_get_match_stats()` error message

- DESCRIPTION
- NEWS.md
- R/fotmob_players.R
- tests/testthat/test-fotmob.R
Fix bug with `fotmob_get_match_players` returning list-columns for `stat` columns. (#298)
Before (note the `<list<chr>>`)
```r
library(worldfootballR)
packageVersion("worldfootballR")
#> [1] '0.6.3.9'
players <- fotmob_get_match_players(3846347)
dplyr::select(players, dplyr::starts_with("stats_")) |> dplyr::glimpse()
#> Rows: 46
#> Columns: 42
#> $ stats_fot_mob_rating                 <list<chr>> "5.01", <"7.79", "5.99", "6…
#> $ stats_minutes_played                 <list<chr>> "90", <"90", "90", "90", "9…
#> $ stats_saves                          <list<chr>> "5", <NULL>, <NULL>, <NULL>…
#> $ stats_goals_conceded                 <list<chr>> "3", <NULL>, <NULL>, <NULL>…
#> $ stats_x_got_faced                    <list<chr>> "4.39", <NULL>, <NULL>, <NU…
#> $ stats_accurate_passes …
```
> Fix `fotmob_get_match_players` stat nesting

- DESCRIPTION
- NEWS.md
- R/fotmob_players.R
Bug fixes for `fotmob_get_match_players()`
1. Remove hard-coded by-row assignment in `fotmob_get_match_players()` (fixes #298)
2. Fix failure in cases where players do not have stats (observed in [recent R CMD check](https://github.com/JaseZiv/worldfootballR/actions/runs/5570217380/job/15082665666))
> Bug fixes for `fotmob_get_match_players()`

- DESCRIPTION
- NEWS.md
- R/fb_league_stats.R
- man/fb_league_stats.Rd
- tests/testthat/test-fbref.R
Regarding issue #319, the specific bug reported was probably due to promises not working properly. That said, for what I can see the non_dom_league_url param is not actually used inside the fb_league_stats() function. I've implemented the same approach as fb_match_results() to try and fix that.
> Fix for fb_league_stats() regarding non-dom-leagues

- DESCRIPTION
- NEWS.md
- R/fb_league_stats.R
The `fb_player_stats()` function seemed to be pulling the wrong season URL for the Australian men's 1st tier league, for the 2023 season. This is because our season URL CSV is still marking the 2022-23 season as the current season.
While we could just try to make our processes around indicating the prompt season in the CSV more robust, an alternative, possibly less fragile approach is to construct the season URL from the competition URL and the season name (using the same CSV's data). We can always rely on the "full" season URL being correct, even with a competition's current season.
For example, the player playing time URL for the aforementioned league can be referred to both as `https://fbref.com/en/comps/65/2023-2024/playingtime/2023-2024-A-League-Men-Stats` or just …
> Fix `fb_player_stats()` bug with current seasons

- DESCRIPTION
- NEWS.md
- R/fb_league_stats.R
Fixes #355.
Code below returns 36 rows instead of 18, which it was incorrectly doing before.
```r
library(worldfootballR)
packageVersion('worldfootballR')
#> [1] '0.6.5.1'
data <- fb_league_stats(
country = c("POR"),
gender = "M",
season_end_year = 2024,
stat_type = "shooting",
team_or_player = "team"
)
dplyr::glimpse(data)
#> Rows: 36
#> Columns: 22
#> $ Team_or_Opponent         <chr> "team", "team", "team", "team", "team", "team…
#> $ Squad                    <chr> "Arouca", "Benfica", "Boavista", "Braga", "Ca…
#> $ Num_Players              <int> 25, 28, 23, 23, 26, 28, 25, 27, 23, 23, 27, 2…
#> $ Mins_Per_90              <dbl> 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 1…
#> $ Gls_Standard             <int> 22, 34, 24, 39, 18, 18, 31, 16, 17, 23, 27, 2…
#> $ Sh_Standard …
```
> Fix bug with retrieving opponent team stats with `fb_league_stats`

- DESCRIPTION
- NEWS.md
- R/tm_player_injury_history.R
Mark Carey found a bug in the `tm_player_injury_history` function where by it was recursively adding rows when there were two flags in the `club` column.
> addressing #375

- DESCRIPTION
- NEWS.md
- R/get_season_team_stats.R
Fixes #389. Prior PR assumed that `competition_name` in `all_seasons.csv` would match what is shown on the FBRef page, but that doesn't always turn out to be the case, e.g. Bundesliga. I've made a change to remove string searching, and instead assume the points table is always the first on the page. I'm 99% sure that this should work for all leagues, although I haven't tested it comprehensively.
Confirmed that this works.
```r
fb_season_team_stats(
country = c("ENG", "ESP", "GER", "ITA", "FRA", "USA"),
gender = "M",
season_end_year = c(2013:2024),
tier = "1st",
stat_type = "league_table",
time_pause = 5
)
```
> always choose the first table

- DESCRIPTION
- NEWS.md
- R/tm_expiring_contracts.R
The date of birth / age column is currently the only variable that is not present when scraping expiring contracts using `tm_expiring_contracts` function. 
This is a simple enhancement that adds the html for date of birth and processes it akin to the other columns.
> Enhancement suggestion: Add date of birth to `tm_expiring_contracts`

- vignettes/load-scraped-data.Rmd
Related to comment [here](https://github.com/JaseZiv/worldfootballR/pull/427#issuecomment-2768928793).
The problem was that this function call
```r
load_fb_advanced_match_stats(
country = c("ITA", "FRA"),
gender = "M",
tier = "1st",
season_end_year = 2019,
stat_type = "defense",
team_or_player = "player"
)
```
would have an issue combining results from Italy and Spain because Spain's data had numerics for fields that Italy had characters for, e.g. `Home_Score`. I should come up with a solution for that, but in the meantime, we can use a different country in the example to fix the issue.
Showing success on local `pkgdown::build_site()`. (Not committing results since our `gh-pages` branch hosts the changes.
> Update load-scraped-data.Rmd to fix pkgdown build

- DESCRIPTION
- NEWS.md
- R/tm_team_transfers.R
Fixes #433.
Issue was being caused by empty section for `Transfermarkt Videos` h2 header, so a subsequent call to `html_nodes()` (renamed to `html_elements()` in newer versions for `{rvest}`) was discarding one of the h2 headers, which resulted in incorrect indexing when plucking out the `Departures` section. Using `html_element()` instead of `html_elements()` solves the problem. Per `{rvest}` docs:
```
html_element() returns a nodeset the same length as the input.
html_elements() flattens the output so there's no direct way to map the output to the input.
```
> bugfix: `tm_team_transfer()` returns both Arrivals and Departures
